name: powerset
description: Generate the powerset of any iterable.
version: 0.0.1
author: Harry Terkelsen <harry@terkelsen.io>
homepage: https://github.com/hterkelsen/powerset

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
