name: powerset
description: A utility function for generating the powerset of an iterable.
  This generates all subsequences of an iterable, even for infinite iterables.
version: 1.1.0
homepage: https://github.com/hterkelsen/powerset

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
