name: powerset
description: Generate the powerset of any iterable.
version: 0.0.2
homepage: https://github.com/hterkelsen/powerset

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.9.0
